--Step 1: Extract Expensive Queries

CREATE OR REPLACE TABLE TOP_EXPENSIVE_QUERIES AS
SELECT 
QUERY_ID,
QUERY_TEXT,
TOTAL_ELAPSED_TIME/1000 AS EXECUTION_SECONDS,
BYTES_SCANNED,
WAREHOUSE_NAME,
USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
AND BYTES_SCANNED > 1e9
ORDER BY BYTES_SCANNED DESC
LIMIT 100;

--Step 2: Cortex Prompt for Optimization

CREATE OR REPLACE TABLE QUERY_OPTIMIZATION_RESULTS AS
SELECT 
QUERY_ID,
QUERY_TEXT,
SNOWFLAKE.CORTEX.COMPLETE(
'mistral-large',
CONCAT(
'You are a Snowflake SQL optimization expert. 
Optimize the below query for cost and performance.
1. Reduce data scan
2. Avoid SELECT *
3. Suggest partition pruning
4. Improve joins
Query:
', QUERY_TEXT
)
) AS OPTIMIZED_QUERY
FROM TOP_EXPENSIVE_QUERIES;

--Step 3: Add Explanation Layer

ALTER TABLE QUERY_OPTIMIZATION_RESULTS ADD COLUMN EXPLANATION STRING;

UPDATE QUERY_OPTIMIZATION_RESULTS
SET EXPLANATION = SNOWFLAKE.CORTEX.COMPLETE(
'mistral-large',
CONCAT(
'Explain why this query is inefficient and what improvements were made:
Original: ', QUERY_TEXT,
' Optimized: ', OPTIMIZED_QUERY
)
);

--Automation Layer (Critical)
--Use Snowflake Tasks
CREATE TASK DAILY_OPTIMIZATION_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
CALL RUN_GENAI_OPTIMIZATION();

--Optional: Stored Procedure Wrapper
--Bundle logic:

CREATE OR REPLACE PROCEDURE RUN_GENAI_OPTIMIZATION()
RETURNS STRING
LANGUAGE SQL
AS
$
BEGIN
-- Refresh top queries
-- Run Cortex optimization
-- Store results
RETURN 'Done';
END;

