-- Detect warehouse cost spikes and explain them with Cortex AI

--Step 1: Aggregate Daily Cost

CREATE OR REPLACE TABLE DAILY_WAREHOUSE_COST AS
SELECT 
WAREHOUSE_NAME,
DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
GROUP BY 1,2;

--Step 2: Detect Spikes

CREATE OR REPLACE TABLE COST_SPIKES AS
SELECT *,
LAG(TOTAL_CREDITS) OVER (PARTITION BY WAREHOUSE_NAME ORDER BY USAGE_DATE) AS PREV_DAY,
(TOTAL_CREDITS - LAG(TOTAL_CREDITS) OVER (PARTITION BY WAREHOUSE_NAME ORDER BY USAGE_DATE)) AS SPIKE
FROM DAILY_WAREHOUSE_COST
QUALIFY TOTAL_CREDITS > LAG(TOTAL_CREDITS) OVER (PARTITION BY WAREHOUSE_NAME ORDER BY USAGE_DATE) * 1.5;

--Step 3: Cortex Explanation 

CREATE OR REPLACE TABLE COST_INSIGHTS AS
SELECT 
WAREHOUSE_NAME,
USAGE_DATE,
SPIKE,
SNOWFLAKE.CORTEX.COMPLETE(
'mistral-large',
CONCAT(
'Explain why Snowflake cost spiked.
Consider query patterns, large scans, joins, dashboards, ETL jobs.
Warehouse: ', WAREHOUSE_NAME,
' Date: ', USAGE_DATE,
' Spike: ', SPIKE
)
) AS COST_EXPLANATION
FROM COST_SPIKES;


--Step 4: Enrich with Query Context

--Join:
--SQL
QUERY_HISTORY WHERE DATE = SPIKE_DATE

--Automation Layer (Critical)
--Use Snowflake Tasks
CREATE TASK DAILY_OPTIMIZATION_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
CALL RUN_GENAI_OPTIMIZATION();

--Optional: Stored Procedure Wrapper
--Bundle logic:

CREATE OR REPLACE PROCEDURE RUN_GENAI_OPTIMIZATION()
RETURNS STRING
LANGUAGE SQL
AS
$
BEGIN
-- Refresh top queries
-- Run Cortex optimization
-- Store results
RETURN 'Done';
END;
